CC=g++
CFLAGS=-c -march=native -DAVX_IMPLEMENT
LDFLAGS=
SOURCES=main.cpp mandelbrot.cpp
LIBRARIES=-lsfml-graphics -lsfml-window -lsfml-system
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=Mandelbrot

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@ $(LIBRARIES)

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -rf *.o
