CC=g++

CFLAGS=-c -march=native -O3 -DAVX_IMPLEMENT

LDFLAGS=

SOURCES=main.cpp mandelbrot.cpp

LIBRARIES=-lsfml-graphics -lsfml-window -lsfml-system

DEFAULT_OBJECTS=$(SOURCES:.cpp=.o)

EXECUTABLE=Mandelbrot

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(DEFAULT_OBJECTS)
	$(CC) $(LDFLAGS) $(DEFAULT_OBJECTS) -o $@ $(LIBRARIES)

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -rf *.o
